/**
 * admin.js - Backoffice for Code 4 All
 * Uses GitHub API to manage posts via data/posts.json
 */

var REPO_OWNER = 'TxeBals';
var REPO_NAME = 'CodeForAll';
var POSTS_PATH = 'data/posts.json';
var ghToken = '';
var postsData = null;
var fileSha = '';

// ── Auth ──

function authenticate() {
  ghToken = document.getElementById('ghToken').value;
  if (!ghToken) return;

  ghFetch('/repos/' + REPO_OWNER + '/' + REPO_NAME)
    .then(function(res) {
      if (res.ok) {
        document.getElementById('loginSection').style.display = 'none';
        document.getElementById('adminPanel').style.display = 'block';
        sessionStorage.setItem('gh-token', ghToken);
        loadPosts();
      } else {
        alert('Token inv\u00e1lido o sin permisos');
      }
    })
    .catch(function(e) {
      alert('Error de conexi\u00f3n: ' + e.message);
    });
}

function logout() {
  sessionStorage.removeItem('gh-token');
  ghToken = '';
  location.reload();
}

// Auto-restore session
(function() {
  var saved = sessionStorage.getItem('gh-token');
  if (saved) {
    ghToken = saved;
    document.getElementById('ghToken').value = saved;
    authenticate();
  }
})();

// ── GitHub API helpers ──

function ghFetch(endpoint, options) {
  options = options || {};
  var headers = {
    'Authorization': 'Bearer ' + ghToken,
    'Accept': 'application/vnd.github.v3+json',
    'Content-Type': 'application/json'
  };
  if (options.headers) {
    Object.keys(options.headers).forEach(function(k) { headers[k] = options.headers[k]; });
  }
  options.headers = headers;
  return fetch('https://api.github.com' + endpoint, options);
}

function loadPosts() {
  ghFetch('/repos/' + REPO_OWNER + '/' + REPO_NAME + '/contents/' + POSTS_PATH)
    .then(function(res) { return res.json(); })
    .then(function(file) {
      fileSha = file.sha;
      var content = decodeURIComponent(escape(atob(file.content.replace(/\n/g, ''))));
      postsData = JSON.parse(content);
      renderPostsList();
    })
    .catch(function(e) {
      alert('Error cargando posts: ' + e.message);
    });
}

function savePosts(commitMessage) {
  var jsonStr = JSON.stringify(postsData, null, 2);
  var content = btoa(unescape(encodeURIComponent(jsonStr)));
  return ghFetch('/repos/' + REPO_OWNER + '/' + REPO_NAME + '/contents/' + POSTS_PATH, {
    method: 'PUT',
    body: JSON.stringify({
      message: commitMessage || 'Admin: actualizaci\u00f3n de posts',
      content: content,
      sha: fileSha
    })
  })
  .then(function(res) { return res.json(); })
  .then(function(result) {
    if (result.content && result.content.sha) {
      fileSha = result.content.sha;
    }
    return result;
  });
}

// ── CRUD ──

function renderPostsList() {
  var container = document.getElementById('postsSection');
  var html = '<h2>Todos los Posts (' + postsData.posts.length + ')</h2>';

  postsData.posts.forEach(function(post, index) {
    html += '<div class="admin-post-card">' +
      '<div class="post-info">' +
      '<span class="badge ' + (post.autoGenerated ? 'badge-auto-admin' : 'badge-manual') + '">' +
      (post.autoGenerated ? 'Auto' : 'Manual') + '</span>' +
      '<span class="badge badge-cat">' + post.folder + '</span>' +
      '<strong>' + post.title + '</strong>' +
      '<small>' + (post.dateDisplay || post.date) + '</small>' +
      '</div>' +
      '<div class="post-actions">' +
      '<button class="btn-edit" onclick="editPost(' + index + ')">Editar</button>' +
      '<button class="btn-delete" onclick="deletePost(' + index + ')">Eliminar</button>' +
      '</div>' +
      '</div>';
  });

  container.innerHTML = html;
}

function renderNewsList() {
  var container = document.getElementById('newsSection');
  var autoNews = postsData.posts.filter(function(p) { return p.autoGenerated; });
  var html = '<h2>Noticias Auto-generadas (' + autoNews.length + ')</h2>';

  if (autoNews.length === 0) {
    html += '<p>No hay noticias auto-generadas a\u00fan.</p>';
  } else {
    autoNews.forEach(function(post) {
      var idx = postsData.posts.indexOf(post);
      html += '<div class="admin-post-card">' +
        '<div class="post-info">' +
        '<span class="badge badge-auto-admin">Auto</span>' +
        '<span class="badge badge-cat">' + (post.category || post.folder) + '</span>' +
        '<strong>' + post.title + '</strong>' +
        '<small>' + (post.dateDisplay || post.date) + '</small>' +
        (post.sourceUrl ? ' <a href="' + post.sourceUrl + '" target="_blank" class="source-link-admin">' + (post.sourceName || 'Fuente') + '</a>' : '') +
        '</div>' +
        '<div class="post-actions">' +
        '<button class="btn-edit" onclick="editPost(' + idx + ')">Editar</button>' +
        '<button class="btn-delete" onclick="deletePost(' + idx + ')">Eliminar</button>' +
        '</div>' +
        '</div>';
    });
  }

  container.innerHTML = html;
}

function editPost(index) {
  var post = postsData.posts[index];
  showEditForm(post, function(updatedPost) {
    postsData.posts[index] = updatedPost;
    savePosts('Admin: editado "' + updatedPost.title + '"')
      .then(function() {
        renderPostsList();
        showSection('posts');
        alert('Post actualizado y commiteado');
      });
  });
}

function deletePost(index) {
  var post = postsData.posts[index];
  if (!confirm('\u00bfEliminar "' + post.title + '"?')) return;
  postsData.posts.splice(index, 1);
  savePosts('Admin: eliminado "' + post.title + '"')
    .then(function() {
      renderPostsList();
      alert('Post eliminado');
    });
}

function createPost(formData) {
  var maxId = Math.max.apply(null, postsData.posts.map(function(p) { return p.id; }).concat([0]));
  formData.id = maxId + 1;
  formData.slug = slugify(formData.title);
  formData.source = 'manual';
  formData.autoGenerated = false;
  formData.url = 'post.html?slug=' + formData.slug;

  postsData.posts.unshift(formData);
  savePosts('Admin: nuevo post "' + formData.title + '"')
    .then(function() {
      renderPostsList();
      showSection('posts');
      alert('Post creado y commiteado');
    });
}

// ── Trigger manual del cron ──

function triggerNewsAction() {
  if (!confirm('\u00bfEjecutar el job de noticias ahora?')) return;
  ghFetch('/repos/' + REPO_OWNER + '/' + REPO_NAME + '/actions/workflows/daily-news.yml/dispatches', {
    method: 'POST',
    body: JSON.stringify({ ref: 'master' })
  })
  .then(function(res) {
    if (res.ok || res.status === 204) {
      alert('Job de noticias disparado. Tardar\u00e1 ~2 minutos. Recarga despu\u00e9s.');
    } else {
      alert('Error disparando el job: ' + res.status);
    }
  })
  .catch(function(e) {
    alert('Error: ' + e.message);
  });
}

// ── Forms UI ──

function showEditForm(post, onSave) {
  var container = document.getElementById('editSection');
  var contentJson = '';
  try {
    contentJson = JSON.stringify(post.content || [], null, 2);
  } catch (e) {
    contentJson = '[]';
  }

  container.innerHTML = '<h2>Editar Post</h2>' +
    '<form id="editForm" class="admin-form">' +
    '<label>T\u00edtulo</label>' +
    '<input type="text" id="editTitle" value="' + escapeAttr(post.title) + '">' +
    '<label>Descripci\u00f3n</label>' +
    '<textarea id="editDesc" rows="3">' + escapeHtml(post.description) + '</textarea>' +
    '<label>Fecha (YYYY-MM-DD)</label>' +
    '<input type="text" id="editDate" value="' + post.date + '">' +
    '<label>Fecha Display</label>' +
    '<input type="text" id="editDateDisplay" value="' + escapeAttr(post.dateDisplay || '') + '">' +
    '<label>Folder / Categor\u00eda</label>' +
    '<input type="text" id="editFolder" value="' + escapeAttr(post.folder) + '">' +
    '<label>Imagen</label>' +
    '<input type="text" id="editImage" value="' + escapeAttr(post.image) + '">' +
    '<label>Tags (separados por coma)</label>' +
    '<input type="text" id="editTags" value="' + (post.tags || []).join(', ') + '">' +
    (post.autoGenerated ?
      '<label>Source URL</label>' +
      '<input type="text" id="editSourceUrl" value="' + escapeAttr(post.sourceUrl || '') + '">' +
      '<label>Source Name</label>' +
      '<input type="text" id="editSourceName" value="' + escapeAttr(post.sourceName || '') + '">'
      : '') +
    '<label>Contenido (JSON array de bloques)</label>' +
    '<textarea id="editContent" rows="12">' + escapeHtml(contentJson) + '</textarea>' +
    '<div class="form-buttons">' +
    '<button type="button" onclick="saveEditForm()">Guardar</button>' +
    '<button type="button" class="btn-cancel" onclick="showSection(\'posts\')">Cancelar</button>' +
    '</div>' +
    '</form>';

  showSection('edit');

  // Store callback
  window._editSaveCallback = onSave;
  window._editPostOriginal = post;
}

function saveEditForm() {
  var updated = Object.assign({}, window._editPostOriginal);
  updated.title = document.getElementById('editTitle').value;
  updated.description = document.getElementById('editDesc').value;
  updated.date = document.getElementById('editDate').value;
  updated.dateDisplay = document.getElementById('editDateDisplay').value;
  updated.folder = document.getElementById('editFolder').value;
  updated.image = document.getElementById('editImage').value;
  updated.tags = document.getElementById('editTags').value.split(',').map(function(t) { return t.trim(); }).filter(Boolean);
  updated.slug = slugify(updated.title);

  if (updated.autoGenerated) {
    var srcUrl = document.getElementById('editSourceUrl');
    var srcName = document.getElementById('editSourceName');
    if (srcUrl) updated.sourceUrl = srcUrl.value;
    if (srcName) updated.sourceName = srcName.value;
  }

  try {
    updated.content = JSON.parse(document.getElementById('editContent').value);
  } catch (e) {
    alert('Error en el JSON del contenido: ' + e.message);
    return;
  }

  if (window._editSaveCallback) {
    window._editSaveCallback(updated);
  }
}

function showNewForm() {
  var container = document.getElementById('newSection');
  container.innerHTML = '<h2>Nuevo Post</h2>' +
    '<form id="newForm" class="admin-form">' +
    '<label>T\u00edtulo</label>' +
    '<input type="text" id="newTitle" placeholder="T\u00edtulo del post">' +
    '<label>Descripci\u00f3n</label>' +
    '<textarea id="newDesc" rows="3" placeholder="Descripci\u00f3n breve"></textarea>' +
    '<label>Fecha (YYYY-MM-DD)</label>' +
    '<input type="text" id="newDate" value="' + new Date().toISOString().split('T')[0] + '">' +
    '<label>Fecha Display</label>' +
    '<input type="text" id="newDateDisplay" value="' + formatDateSpanish(new Date().toISOString().split('T')[0]) + '">' +
    '<label>Folder / Categor\u00eda</label>' +
    '<input type="text" id="newFolder" placeholder="AI, Azure, AKS...">' +
    '<label>Imagen</label>' +
    '<input type="text" id="newImage" value="images/posts/ai-news-default.svg">' +
    '<label>Tags (separados por coma)</label>' +
    '<input type="text" id="newTags" placeholder="tag1, tag2, tag3">' +
    '<label>Contenido (JSON array de bloques)</label>' +
    '<textarea id="newContent" rows="12" placeholder=\'[{"type": "t", "text": "#1. T\u00edtulo"}, {"type": "p", "text": "P\u00e1rrafo..."}]\'></textarea>' +
    '<div class="form-buttons">' +
    '<button type="button" onclick="submitNewForm()">Crear Post</button>' +
    '<button type="button" class="btn-cancel" onclick="showSection(\'posts\')">Cancelar</button>' +
    '</div>' +
    '</form>';
}

function submitNewForm() {
  var title = document.getElementById('newTitle').value;
  if (!title) { alert('El t\u00edtulo es obligatorio'); return; }

  var contentText = document.getElementById('newContent').value;
  var content = [];
  if (contentText) {
    try {
      content = JSON.parse(contentText);
    } catch (e) {
      alert('Error en el JSON del contenido: ' + e.message);
      return;
    }
  }

  createPost({
    date: document.getElementById('newDate').value,
    dateDisplay: document.getElementById('newDateDisplay').value,
    title: title,
    description: document.getElementById('newDesc').value,
    image: document.getElementById('newImage').value,
    folder: document.getElementById('newFolder').value,
    tags: document.getElementById('newTags').value.split(',').map(function(t) { return t.trim(); }).filter(Boolean),
    content: content
  });
}

function showSection(section) {
  var sections = ['postsSection', 'newsSection', 'statsSection', 'newSection', 'editSection'];
  sections.forEach(function(s) {
    document.getElementById(s).style.display = 'none';
  });
  document.getElementById(section + 'Section').style.display = 'block';

  // Update nav button active state
  document.querySelectorAll('.nav-btn').forEach(function(b) { b.classList.remove('active'); });
  var btnMap = { posts: 0, news: 1, stats: 2, 'new': 3 };
  var navBtns = document.querySelectorAll('.admin-nav-actions .nav-btn');
  if (btnMap[section] !== undefined && navBtns[btnMap[section]]) {
    navBtns[btnMap[section]].classList.add('active');
  }

  if (section === 'new') showNewForm();
  if (section === 'news') renderNewsList();
  if (section === 'stats') renderStats();
}

// ── Stats / Analytics ──

function renderStats() {
  var container = document.getElementById('statsSection');
  if (!container) return;

  var totalViews = (typeof PostAnalytics !== 'undefined') ? PostAnalytics.getTotalViews() : 0;
  var topPosts = (typeof PostAnalytics !== 'undefined') ? PostAnalytics.getTopPosts(20) : [];
  var allViews = (typeof PostAnalytics !== 'undefined') ? PostAnalytics.getAllViews() : {};

  // Build a slug-to-title map from postsData
  var slugToTitle = {};
  var slugToFolder = {};
  if (postsData && postsData.posts) {
    postsData.posts.forEach(function(p) {
      slugToTitle[p.slug] = p.title;
      slugToFolder[p.slug] = p.folder;
    });
  }

  var html = '<h2>Estad\u00edsticas de Visitas</h2>';

  // Summary cards
  html += '<div class="stats-summary">' +
    '<div class="stat-card">' +
    '<div class="stat-number">' + totalViews + '</div>' +
    '<div class="stat-label">Visitas totales</div>' +
    '</div>' +
    '<div class="stat-card">' +
    '<div class="stat-number">' + Object.keys(allViews).length + '</div>' +
    '<div class="stat-label">Posts visitados</div>' +
    '</div>' +
    '<div class="stat-card">' +
    '<div class="stat-number">' + (postsData ? postsData.posts.length : 0) + '</div>' +
    '<div class="stat-label">Posts totales</div>' +
    '</div>' +
    '</div>';

  // Info note
  html += '<div class="stats-note">' +
    '<strong>Nota:</strong> Las visitas se registran con localStorage en cada navegador. ' +
    'Estos datos son del navegador actual. Para anal\u00edticas globales, ' +
    'consulta <a href="https://github.com/' + REPO_OWNER + '/' + REPO_NAME + '/graphs/traffic" target="_blank" rel="noopener">' +
    'GitHub Insights &rarr; Traffic</a>.' +
    '</div>';

  // Top posts table
  if (topPosts.length > 0) {
    html += '<h3 class="stats-subtitle">Top Posts por Visitas</h3>';
    html += '<table class="stats-table">' +
      '<thead><tr><th>#</th><th>Post</th><th>Categor\u00eda</th><th>Visitas</th><th>\u00daltima visita</th></tr></thead>' +
      '<tbody>';

    topPosts.forEach(function(item, i) {
      var title = slugToTitle[item.slug] || item.slug;
      var folder = slugToFolder[item.slug] || '-';
      html += '<tr>' +
        '<td>' + (i + 1) + '</td>' +
        '<td title="' + escapeAttr(item.slug) + '">' + escapeHtml(title) + '</td>' +
        '<td><span class="badge badge-cat">' + escapeHtml(folder) + '</span></td>' +
        '<td><strong>' + item.count + '</strong></td>' +
        '<td>' + (item.lastVisit || '-') + '</td>' +
        '</tr>';
    });

    html += '</tbody></table>';
  } else {
    html += '<p>No hay datos de visitas a\u00fan. Las visitas se registran cuando los usuarios leen los posts.</p>';
  }

  // Posts without views
  if (postsData && postsData.posts) {
    var unviewedPosts = postsData.posts.filter(function(p) {
      return !allViews[p.slug] || allViews[p.slug].count === 0;
    });

    if (unviewedPosts.length > 0) {
      html += '<h3 class="stats-subtitle">Posts sin visitas (' + unviewedPosts.length + ')</h3>';
      html += '<div class="unviewed-list">';
      unviewedPosts.forEach(function(p) {
        html += '<span class="unviewed-item">' + escapeHtml(p.title) + '</span>';
      });
      html += '</div>';
    }
  }

  container.innerHTML = html;
}

// ── Helpers ──

function slugify(text) {
  return text.toLowerCase()
    .normalize('NFD').replace(/[\u0300-\u036f]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
    .substring(0, 60);
}

function formatDateSpanish(dateStr) {
  var months = ['Enero','Febrero','Marzo','Abril','Mayo','Junio',
                'Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'];
  var parts = dateStr.split('-');
  return parseInt(parts[2]) + ' de ' + months[parseInt(parts[1]) - 1] + ' de ' + parts[0];
}

function escapeAttr(str) {
  return str.replace(/"/g, '&quot;').replace(/'/g, '&#39;');
}

function escapeHtml(str) {
  return str.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}
