/**
 * posts.js - Dynamic post rendering with filters and pagination
 * Loads data/posts.json and renders posts on index.html
 */

let allPosts = [];
let currentFilter = 'all';
let currentPage = 1;
const POSTS_PER_PAGE = 10;

async function loadPosts() {
  try {
    const res = await fetch('data/posts.json');
    const data = await res.json();
    allPosts = data.posts.sort((a, b) => new Date(b.date) - new Date(a.date));
    renderTodayNews();
    renderFilters();
    renderPosts();
  } catch (e) {
    console.error('Error loading posts:', e);
    document.getElementById('postContainer').innerHTML =
      '<p class="text-danger">Error cargando los posts.</p>';
  }
}

function renderTodayNews() {
  const container = document.getElementById('todayNewsContainer');
  if (!container) return;

  const today = new Date().toISOString().split('T')[0];
  let newsItems = allPosts.filter(p => p.autoGenerated && p.date === today);

  if (newsItems.length === 0) {
    newsItems = allPosts.filter(p => p.autoGenerated).slice(0, 4);
  }

  if (newsItems.length === 0) {
    document.getElementById('todayNews').style.display = 'none';
    return;
  }

  document.getElementById('todayNews').style.display = 'block';
  container.innerHTML = newsItems.map(post => {
    var postUrl = getPostUrl(post);
    return '<div class="today-news-card">' +
      '<a href="' + postUrl + '" class="today-news-img" style="background-image: url(' + post.image + ');"></a>' +
      '<div class="today-news-info">' +
      '<span class="badge-category badge-' + slugifyCategory(post.folder) + '">' + post.folder + '</span>' +
      '<h4><a href="' + postUrl + '">' + post.title + '</a></h4>' +
      '<p class="today-news-meta">' + (post.dateDisplay || post.date) + '</p>' +
      (post.sourceUrl ? '<a href="' + post.sourceUrl + '" target="_blank" rel="noopener" class="source-link">&#128279; ' + (post.sourceName || 'Fuente') + '</a>' : '') +
      '</div>' +
      '</div>';
  }).join('');
}

function renderFilters() {
  const container = document.getElementById('filterContainer');
  if (!container) return;

  const folders = [...new Set(allPosts.map(p => p.folder))].sort();
  const hasAutoNews = allPosts.some(p => p.autoGenerated);

  let html = '<button class="filter-btn active" data-filter="all">Todos</button>';

  if (hasAutoNews) {
    html += '<button class="filter-btn" data-filter="auto-news">Noticias IA</button>';
  }

  folders.forEach(folder => {
    html += '<button class="filter-btn" data-filter="folder-' + folder + '">' + folder + '</button>';
  });

  container.innerHTML = html;

  container.querySelectorAll('.filter-btn').forEach(btn => {
    btn.addEventListener('click', function () {
      container.querySelectorAll('.filter-btn').forEach(b => b.classList.remove('active'));
      this.classList.add('active');
      currentFilter = this.getAttribute('data-filter');
      currentPage = 1;
      renderPosts();
    });
  });
}

function getFilteredPosts() {
  if (currentFilter === 'all') return allPosts;
  if (currentFilter === 'auto-news') return allPosts.filter(p => p.autoGenerated);
  if (currentFilter.startsWith('folder-')) {
    var folder = currentFilter.replace('folder-', '');
    return allPosts.filter(p => p.folder === folder);
  }
  return allPosts;
}

function renderPosts() {
  var filtered = getFilteredPosts();
  var totalPages = Math.ceil(filtered.length / POSTS_PER_PAGE);
  var start = (currentPage - 1) * POSTS_PER_PAGE;
  var paginated = filtered.slice(start, start + POSTS_PER_PAGE);

  var container = document.getElementById('postContainer');
  if (!container) return;

  if (paginated.length === 0) {
    container.innerHTML = '<div class="col-md-12"><p>No hay posts en esta categor&iacute;a.</p></div>';
    renderPagination(0);
    return;
  }

  container.innerHTML = paginated.map(function (post) {
    return mountPostCard(post);
  }).join('');

  renderPagination(totalPages);

  // Re-trigger waypoint animations
  if (typeof contentWayPoint === 'function') {
    contentWayPoint();
  }
}

function mountPostCard(post) {
  var postUrl = getPostUrl(post);
  var badges = '';

  if (post.autoGenerated) {
    badges += '<span class="badge-auto">&#129302; IA</span>';
  }
  badges += '<span class="badge-category badge-' + slugifyCategory(post.folder) + '">' + post.folder + '</span>';

  var sourceLink = '';
  if (post.autoGenerated && post.sourceUrl) {
    sourceLink = '<a href="' + post.sourceUrl + '" target="_blank" rel="noopener" class="source-link">&#128279; ' + (post.sourceName || 'Fuente') + '</a>';
  }

  var tagsHtml = '';
  if (post.tags && post.tags.length > 0) {
    tagsHtml = '<div class="post-tags">' +
      post.tags.map(function (t) { return '<span class="post-tag">' + t + '</span>'; }).join('') +
      '</div>';
  }

  return '<div class="col-md-12">' +
    '<div class="blog-entry ftco-animate d-md-flex fadeInUp ftco-animated">' +
    '<a href="' + postUrl + '" class="img img-2" style="background-image: url(' + post.image + ');"></a>' +
    '<div class="text text-2 pl-md-4">' +
    '<div class="post-badges">' + badges + '</div>' +
    '<h3 class="mb-2"><a href="' + postUrl + '">' + post.title + '</a></h3>' +
    '<div class="meta-wrap">' +
    '<p class="meta">' +
    '<span><i class="icon-calendar mr-2"></i>' + (post.dateDisplay || post.date) + '</span>' +
    '<span><a href="' + postUrl + '"><i class="icon-folder-o mr-2"></i>' + post.folder + '</a></span>' +
    '</p>' +
    '</div>' +
    '<p class="mb-2">' + post.description + '</p>' +
    sourceLink +
    tagsHtml +
    '<p><a href="' + postUrl + '" class="btn-custom">Leer m&aacute;s <span class="ion-ios-arrow-forward"></span></a></p>' +
    '</div>' +
    '</div>' +
    '</div>';
}

function getPostUrl(post) {
  // Legacy posts use direct HTML files, new posts use post.html?slug=
  if (post.url && post.url.indexOf('post.html?slug=') !== -1) {
    return post.url;
  }
  if (post.url) {
    return post.url;
  }
  return 'post.html?slug=' + post.slug;
}

function renderPagination(totalPages) {
  var paginationContainer = document.getElementById('paginationContainer');
  if (!paginationContainer) return;

  if (totalPages <= 1) {
    paginationContainer.innerHTML = '';
    return;
  }

  var html = '<ul>';

  if (currentPage > 1) {
    html += '<li><a href="#" data-page="' + (currentPage - 1) + '">&lt;</a></li>';
  }

  for (var i = 1; i <= totalPages; i++) {
    if (i === currentPage) {
      html += '<li class="active"><span>' + i + '</span></li>';
    } else {
      html += '<li><a href="#" data-page="' + i + '">' + i + '</a></li>';
    }
  }

  if (currentPage < totalPages) {
    html += '<li><a href="#" data-page="' + (currentPage + 1) + '">&gt;</a></li>';
  }

  html += '</ul>';
  paginationContainer.innerHTML = html;

  paginationContainer.querySelectorAll('a[data-page]').forEach(function (link) {
    link.addEventListener('click', function (e) {
      e.preventDefault();
      currentPage = parseInt(this.getAttribute('data-page'));
      renderPosts();
      window.scrollTo({ top: 0, behavior: 'smooth' });
    });
  });
}

function slugifyCategory(text) {
  return text.toLowerCase()
    .normalize('NFD').replace(/[\u0300-\u036f]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
}

document.addEventListener('DOMContentLoaded', loadPosts);
