const Anthropic = require('@anthropic-ai/sdk');
const fs = require('fs');
const path = require('path');

const client = new Anthropic({
  maxRetries: 0,
  defaultHeaders: {
    'anthropic-unsafe-disable-streaming': 'true'
  }
});
const POSTS_FILE = path.join(__dirname, '..', 'data', 'posts.json');
const POSTS_DIR = path.join(__dirname, '..', 'posts');

// Ensure posts/ directory exists
if (!fs.existsSync(POSTS_DIR)) fs.mkdirSync(POSTS_DIR, { recursive: true });

// ── Rate-limit aware API call with retry ──

async function callAPI(params, label) {
  const MAX_RETRIES = 2;
  for (let attempt = 1; attempt <= MAX_RETRIES; attempt++) {
    try {
      console.log('[API] ' + label + ' (intento ' + attempt + ')...');
      const response = await client.messages.create(params);
      return response;
    } catch (e) {
      if (attempt < MAX_RETRIES) {
        const waitSecs = 20 * attempt;
        console.log('[Error] ' + (e.message || e.code || e.status) + ' - Intento ' + attempt + '/' + MAX_RETRIES + ', esperando ' + waitSecs + 's...');
        await sleep(waitSecs * 1000);
      } else {
        throw e;
      }
    }
  }
  throw new Error('Agotados todos los reintentos para: ' + label);
}

function sleep(ms) {
  return new Promise(r => setTimeout(r, ms));
}

// ── Robust JSON array extraction ──
function extractJSONArray(text) {
  // Strategy 1: Direct parse (best case)
  try {
    const parsed = JSON.parse(text);
    if (Array.isArray(parsed)) return parsed;
  } catch (_) {}

  // Strategy 2: Find the outermost [...] with bracket balancing
  const startIdx = text.indexOf('[');
  if (startIdx !== -1) {
    let depth = 0;
    let inString = false;
    let escape = false;
    for (let i = startIdx; i < text.length; i++) {
      const ch = text[i];
      if (escape) { escape = false; continue; }
      if (ch === '\\' && inString) { escape = true; continue; }
      if (ch === '"') { inString = !inString; continue; }
      if (inString) continue;
      if (ch === '[') depth++;
      if (ch === ']') {
        depth--;
        if (depth === 0) {
          const candidate = text.substring(startIdx, i + 1);
          try {
            const parsed = JSON.parse(candidate);
            if (Array.isArray(parsed)) return parsed;
          } catch (_) {}
          break;
        }
      }
    }
  }

  // Strategy 3: Extract individual JSON objects and build array
  const objects = [];
  const objRegex = /\{[^{}]*(?:\{[^{}]*\}[^{}]*)*\}/g;
  let m;
  while ((m = objRegex.exec(text)) !== null) {
    try {
      const obj = JSON.parse(m[0]);
      if (obj.title && obj.description) objects.push(obj);
    } catch (_) {}
  }
  if (objects.length > 0) {
    console.log('[Parse] Recuperados ' + objects.length + ' items via extraccion individual');
    return objects;
  }

  throw new Error('No se pudo extraer JSON array valido del response');
}

async function main() {
  const today = new Date().toISOString().split('T')[0];
  console.log('Buscando noticias de IA para ' + today + '...');

  // ── CHECK: Si ya hay noticias de hoy, no gastar API ──
  const existingData = JSON.parse(fs.readFileSync(POSTS_FILE, 'utf8'));
  const todayNews = existingData.posts.filter(p => p.autoGenerated && p.date === today);
  if (todayNews.length > 0) {
    console.log('⏭️ Ya existen ' + todayNews.length + ' noticias de hoy (' + today + '). Saltando fetch para no gastar API.');
    generateSitemap(existingData.posts);
    generateRSS(existingData.posts);
    console.log('Proceso completado (sin llamadas a API)');
    return;
  }

  // ── STEP 1: Generate news ──
  const searchResponse = await callAPI({
    model: 'claude-opus-4-1-20250805',
    max_tokens: 1500,
    messages: [{
      role: 'user',
      content: 'Genera 4 noticias TECNICAS realistas sobre IA para desarrolladores, año 2026.\n\n' +
        'Criterios: frameworks nuevos, APIs, updates herramientas dev, repos IA trending.\n' +
        'Evitar: politica, regulacion, ficcion pura.\n\n' +
        'JSON array SOLO:\n' +
        '[{"title":"...",\n"description":"...",\n"sourceUrl":"https://...",\n"sourceName":"...",\n"category":"LLM|AGENTES|HERRAMIENTAS|GITHUB_REPO|BUENAS_PRACTICAS|INVESTIGACION",\n"tags":["..."],\n"keyPoints":["..."]}]'
    }]
  }, 'Generacion de noticias');

  const rawText = searchResponse.content.filter(b => b.type === 'text').map(b => b.text).join('\n');
  const cleanText = rawText.replace(/```json|```/g, '').trim();

  let newsItems;
  try {
    newsItems = extractJSONArray(cleanText);
  } catch (e) {
    console.error('Error parseando noticias:', e.message);
    console.log('Raw response (primeros 500 chars):', cleanText.substring(0, 500));
    process.exit(1);
  }

  if (!newsItems || newsItems.length === 0) {
    console.error('No se encontraron noticias validas');
    process.exit(1);
  }

  console.log('Encontradas ' + newsItems.length + ' noticias');

  const postsData = JSON.parse(fs.readFileSync(POSTS_FILE, 'utf8'));
  const maxId = Math.max(...postsData.posts.map(p => p.id), 0);

  // ── STEP 2: Generate articles ──
  console.log('[Pausa] Esperando 20s antes de generar articulos...');
  await sleep(20000);

  for (let i = 0; i < newsItems.length; i++) {
    const item = newsItems[i];
    const newId = maxId + i + 1;
    const slug = slugify(item.title);

    console.log('Generando articulo ' + (i + 1) + '/' + newsItems.length + ': ' + item.title);

    let contentBlocks;
    try {
      const articleResponse = await callAPI({
        model: 'claude-haiku-4-5-20251001',
        max_tokens: 1000,
        messages: [{
          role: 'user',
          content: 'Articulo breve (150-200 palabras) sobre: ' + item.title + '\n' +
            'Descripcion: ' + item.description + '\n\n' +
            'JSON array de bloques SOLO:\n' +
            '[{"type":"t","text":"#1. Titulo"},{"type":"p","text":"Parrafo..."}]'
        }]
      }, 'Articulo ' + (i + 1));

      const articleText = articleResponse.content.filter(b => b.type === 'text').map(b => b.text).join('\n');
      const artClean = articleText.replace(/```json|```/g, '').trim();
      contentBlocks = extractJSONArray(artClean);
    } catch (e) {
      console.warn('Error en articulo ' + (i + 1) + ', usando fallback');
      contentBlocks = [
        { type: 't', text: '#1. ' + item.title },
        { type: 'p', text: item.description }
      ];
    }

    const newPost = {
      id: newId,
      date: today,
      dateDisplay: formatDateSpanish(today),
      title: item.title,
      slug: slug,
      description: item.description,
      image: getCategoryImage(item.category),
      url: 'post.html?slug=' + slug,
      folder: item.category,
      source: 'auto',
      autoGenerated: true,
      sourceUrl: item.sourceUrl,
      sourceName: item.sourceName,
      category: item.category,
      content: contentBlocks,
      tags: item.tags || []
    };

    postsData.posts.unshift(newPost);

    if (i < newsItems.length - 1) {
      console.log('[Pausa] Esperando 20s entre articulos...');
      await sleep(20000);
    }
  }

  fs.writeFileSync(POSTS_FILE, JSON.stringify(postsData, null, 2), 'utf8');
  console.log('posts.json actualizado con ' + newsItems.length + ' noticias nuevas');

  generateSitemap(postsData.posts);
  generateRSS(postsData.posts);

  console.log('Proceso completado');
}

// ── Helpers ──

function slugify(text) {
  return text
    .toLowerCase()
    .normalize('NFD').replace(/[\u0300-\u036f]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
    .substring(0, 60);
}

function formatDateSpanish(dateStr) {
  const months = ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio',
                  'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'];
  const [y, m, d] = dateStr.split('-');
  return parseInt(d) + ' de ' + months[parseInt(m) - 1] + ' de ' + y;
}

function getCategoryImage(category) {
  const images = {
    LLM: 'images/posts/llm-default.svg',
    AGENTES: 'images/posts/agents-default.svg',
    HERRAMIENTAS: 'images/posts/tools-default.svg',
    GITHUB_REPO: 'images/posts/github-default.svg',
    BUENAS_PRACTICAS: 'images/posts/best-practices-default.svg',
    INVESTIGACION: 'images/posts/research-default.svg',
  };
  return images[category] || 'images/posts/ai-news-default.svg';
}

function generateSitemap(posts) {
  let xml = '<?xml version="1.0" encoding="UTF-8"?>\n';
  xml += '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n';
  xml += '  <url><loc>https://txemagonzalez.com/</loc><priority>1.0</priority></url>\n';
  xml += '  <url><loc>https://txemagonzalez.com/about.html</loc><priority>0.8</priority></url>\n';
  posts.forEach(p => {
    const loc = 'https://txemagonzalez.com/' + p.url;
    xml += '  <url><loc>' + loc + '</loc><lastmod>' + p.date + '</lastmod></url>\n';
  });
  xml += '</urlset>';
  fs.writeFileSync(path.join(__dirname, '..', 'sitemap.xml'), xml, 'utf8');
  console.log('sitemap.xml generado');
}

function generateRSS(posts) {
  const recentPosts = posts
    .sort((a, b) => new Date(b.date) - new Date(a.date))
    .slice(0, 20);

  let rss = '<?xml version="1.0" encoding="UTF-8"?>\n';
  rss += '<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">\n';
  rss += '<channel>\n';
  rss += '  <title>Code 4 All - Txema González Balseiro</title>\n';
  rss += '  <link>https://txemagonzalez.com/</link>\n';
  rss += '  <description>Blog de desarrollo, IA y Azure</description>\n';
  rss += '  <language>es</language>\n';
  rss += '  <atom:link href="https://txemagonzalez.com/feed.xml" rel="self" type="application/rss+xml"/>\n';

  recentPosts.forEach(p => {
    const link = 'https://txemagonzalez.com/' + p.url;
    rss += '  <item>\n';
    rss += '    <title>' + escapeXml(p.title) + '</title>\n';
    rss += '    <link>' + escapeXml(link) + '</link>\n';
    rss += '    <description>' + escapeXml(p.description) + '</description>\n';
    rss += '    <pubDate>' + new Date(p.date).toUTCString() + '</pubDate>\n';
    rss += '    <guid>' + escapeXml(link) + '</guid>\n';
    if (p.folder) {
      rss += '    <category>' + escapeXml(p.folder) + '</category>\n';
    }
    rss += '  </item>\n';
  });

  rss += '</channel>\n';
  rss += '</rss>';
  fs.writeFileSync(path.join(__dirname, '..', 'feed.xml'), rss, 'utf8');
  console.log('feed.xml generado');
}

function escapeXml(str) {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

main().catch(e => { console.error('Error fatal:', e); process.exit(1); });
