const Anthropic = require('@anthropic-ai/sdk');
const fs = require('fs');
const path = require('path');

// Mismo modelo que post-linkedin.js (probado con esta API key). Subir a
// 'claude-opus-4-8' si se quiere más calidad y la cuenta tiene acceso.
const MODEL = 'claude-sonnet-4-6';
const POSTS_FILE = path.join(__dirname, '..', 'data', 'posts.json');
const POSTS_DIR = path.join(__dirname, '..', 'posts');

if (!process.env.ANTHROPIC_API_KEY) {
  console.error('❌ Falta ANTHROPIC_API_KEY en env vars');
  process.exit(1);
}

if (!fs.existsSync(POSTS_DIR)) fs.mkdirSync(POSTS_DIR, { recursive: true });

// El SDK lee ANTHROPIC_API_KEY del entorno. maxRetries cubre 429/5xx/errores de red
// con backoff exponencial; timeout amplio porque generamos texto sin streaming.
const client = new Anthropic({ maxRetries: 4, timeout: 120000 });

// ── Llamada a la API de Anthropic vía SDK oficial ──
async function callAnthropicAPI(messages, label, maxTokens = 1500) {
  console.log('[API] ' + label + '...');
  return await client.messages.create({
    model: MODEL,
    max_tokens: maxTokens,
    messages: messages
  });
}

function sleep(ms) {
  return new Promise(r => setTimeout(r, ms));
}

function extractJSONArray(text) {
  try {
    const parsed = JSON.parse(text);
    if (Array.isArray(parsed)) return parsed;
  } catch (_) {}

  const startIdx = text.indexOf('[');
  if (startIdx !== -1) {
    let depth = 0;
    let inString = false;
    let escape = false;
    for (let i = startIdx; i < text.length; i++) {
      const ch = text[i];
      if (escape) { escape = false; continue; }
      if (ch === '\\' && inString) { escape = true; continue; }
      if (ch === '"') { inString = !inString; continue; }
      if (inString) continue;
      if (ch === '[') depth++;
      if (ch === ']') {
        depth--;
        if (depth === 0) {
          const candidate = text.substring(startIdx, i + 1);
          try {
            const parsed = JSON.parse(candidate);
            if (Array.isArray(parsed)) return parsed;
          } catch (_) {}
          break;
        }
      }
    }
  }

  const objects = [];
  const objRegex = /\{[^{}]*(?:\{[^{}]*\}[^{}]*)*\}/g;
  let m;
  while ((m = objRegex.exec(text)) !== null) {
    try {
      const obj = JSON.parse(m[0]);
      if (obj.title && obj.description) objects.push(obj);
    } catch (_) {}
  }
  if (objects.length > 0) {
    console.log('[Parse] Recuperados ' + objects.length + ' items');
    return objects;
  }

  throw new Error('No se pudo extraer JSON array valido del response');
}

async function main() {
  const today = new Date().toISOString().split('T')[0];
  console.log('Buscando noticias de IA para ' + today + '...');

  const existingData = JSON.parse(fs.readFileSync(POSTS_FILE, 'utf8'));
  const todayNews = existingData.posts.filter(p => p.autoGenerated && p.date === today);
  if (todayNews.length > 0) {
    console.log('⏭️ Ya existen ' + todayNews.length + ' noticias de hoy. Saltando.');
    generateSitemap(existingData.posts);
    generateRSS(existingData.posts);
    console.log('Proceso completado');
    return;
  }

  // Generate news
  const newsResponse = await callAnthropicAPI(
    [{
      role: 'user',
      content: 'Genera 4 noticias TECNICAS realistas sobre IA 2026 para developers.\n' +
        'Frameworks, APIs, updates, repos trending.\n\n' +
        'JSON array SOLO:\n' +
        '[{"title":"...","description":"...","sourceUrl":"https://...","sourceName":"...","category":"LLM|AGENTES|HERRAMIENTAS|GITHUB_REPO|BUENAS_PRACTICAS|INVESTIGACION","tags":["..."],"keyPoints":["..."]}]'
    }],
    'Generacion de noticias',
    1200
  );

  const rawText = newsResponse.content[0].text;
  const cleanText = rawText.replace(/```json|```/g, '').trim();

  let newsItems;
  try {
    newsItems = extractJSONArray(cleanText);
  } catch (e) {
    console.error('Error parseando noticias:', e.message);
    console.log('Raw response:', cleanText.substring(0, 300));
    process.exit(1);
  }

  if (!newsItems || newsItems.length === 0) {
    console.error('No se encontraron noticias validas');
    process.exit(1);
  }

  console.log('Encontradas ' + newsItems.length + ' noticias');

  const postsData = JSON.parse(fs.readFileSync(POSTS_FILE, 'utf8'));
  const maxId = Math.max(...postsData.posts.map(p => p.id), 0);

  console.log('[Pausa] 15s antes de generar articulos...');
  await sleep(15000);

  for (let i = 0; i < newsItems.length; i++) {
    const item = newsItems[i];
    const newId = maxId + i + 1;
    const slug = slugify(item.title);

    console.log('Articulo ' + (i + 1) + '/' + newsItems.length);

    let contentBlocks;
    try {
      const artResponse = await callAnthropicAPI(
        [{
          role: 'user',
          content: 'Breve articulo (150 palabras) sobre: ' + item.title + '\n' +
            'JSON array de bloques SOLO:\n' +
            '[{"type":"t","text":"#1. Titulo"},{"type":"p","text":"..."}]'
        }],
        'Articulo ' + (i + 1),
        800
      );

      const artText = artResponse.content[0].text;
      const artClean = artText.replace(/```json|```/g, '').trim();
      contentBlocks = extractJSONArray(artClean);
    } catch (e) {
      console.warn('Fallback para articulo ' + (i + 1));
      contentBlocks = [
        { type: 't', text: '#1. ' + item.title },
        { type: 'p', text: item.description }
      ];
    }

    postsData.posts.unshift({
      id: newId,
      date: today,
      dateDisplay: formatDateSpanish(today),
      title: item.title,
      slug: slug,
      description: item.description,
      image: getCategoryImage(item.category),
      url: 'post.html?slug=' + slug,
      folder: item.category,
      source: 'auto',
      autoGenerated: true,
      sourceUrl: item.sourceUrl,
      sourceName: item.sourceName,
      category: item.category,
      content: contentBlocks,
      tags: item.tags || []
    });

    if (i < newsItems.length - 1) {
      console.log('[Pausa] 15s...');
      await sleep(15000);
    }
  }

  fs.writeFileSync(POSTS_FILE, JSON.stringify(postsData, null, 2), 'utf8');
  console.log('posts.json actualizado');

  generateSitemap(postsData.posts);
  generateRSS(postsData.posts);

  console.log('✅ Completado');
}

function slugify(text) {
  return text
    .toLowerCase()
    .normalize('NFD').replace(/[\u0300-\u036f]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
    .substring(0, 60);
}

function formatDateSpanish(dateStr) {
  const months = ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio',
                  'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'];
  const [y, m, d] = dateStr.split('-');
  return parseInt(d) + ' de ' + months[parseInt(m) - 1] + ' de ' + y;
}

function getCategoryImage(category) {
  const images = {
    LLM: 'images/posts/llm-default.svg',
    AGENTES: 'images/posts/agents-default.svg',
    HERRAMIENTAS: 'images/posts/tools-default.svg',
    GITHUB_REPO: 'images/posts/github-default.svg',
    BUENAS_PRACTICAS: 'images/posts/best-practices-default.svg',
    INVESTIGACION: 'images/posts/research-default.svg',
  };
  return images[category] || 'images/posts/ai-news-default.svg';
}

function generateSitemap(posts) {
  let xml = '<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n';
  xml += '  <url><loc>https://txemagonzalez.com/</loc><priority>1.0</priority></url>\n';
  xml += '  <url><loc>https://txemagonzalez.com/about.html</loc><priority>0.8</priority></url>\n';
  posts.forEach(p => {
    xml += '  <url><loc>https://txemagonzalez.com/' + p.url + '</loc><lastmod>' + p.date + '</lastmod></url>\n';
  });
  xml += '</urlset>';
  fs.writeFileSync(path.join(__dirname, '..', 'sitemap.xml'), xml, 'utf8');
}

function generateRSS(posts) {
  const recent = posts.sort((a, b) => new Date(b.date) - new Date(a.date)).slice(0, 20);
  let rss = '<?xml version="1.0" encoding="UTF-8"?>\n<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">\n<channel>\n';
  rss += '  <title>Code 4 All - Txema González Balseiro</title>\n';
  rss += '  <link>https://txemagonzalez.com/</link>\n';
  rss += '  <description>Blog de desarrollo, IA y Azure</description>\n';
  rss += '  <language>es</language>\n';
  rss += '  <atom:link href="https://txemagonzalez.com/feed.xml" rel="self" type="application/rss+xml"/>\n';
  
  recent.forEach(p => {
    const link = 'https://txemagonzalez.com/' + p.url;
    rss += '  <item><title>' + escapeXml(p.title) + '</title><link>' + escapeXml(link) + '</link>';
    rss += '<description>' + escapeXml(p.description) + '</description><pubDate>' + new Date(p.date).toUTCString() + '</pubDate>';
    rss += '<guid>' + escapeXml(link) + '</guid>';
    if (p.folder) rss += '<category>' + escapeXml(p.folder) + '</category>';
    rss += '</item>\n';
  });
  
  rss += '</channel>\n</rss>';
  fs.writeFileSync(path.join(__dirname, '..', 'feed.xml'), rss, 'utf8');
}

function escapeXml(str) {
  return str.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&apos;');
}

main().catch(e => { console.error('❌ Error:', e.message); process.exit(1); });
